# Generated by Django 6.0.2 on 2026-02-12 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonvideo',
            name='unique_video_order_per_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'], message='Formats autorisés : .mp4, .mkv')]),
        ),
        migrations.DeleteModel(
            name='LessonVideo',
        ),
    ]
