# Generated by Django 6.0.2 on 2026-02-09 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inscription au course'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='chapters/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'], message='erreur. formats autorisés : .mp4, .mkv')]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Contenu ciblé : un concept précis'),
        ),
    ]
